application: vimhelp
version: 1
runtime: python
api_version: 1

handlers:
- url: /update
  script: update.py
  login: admin
- url: /update_de
  script: update_de.py
  login: admin
- url: /testgetfaq
  script: testgetfaq.py
  login: admin
- url: /(?:de/?)?
  script: vimhelp.py
- url: /(?:de/)?(?:.*?\.txt|tags)\.html
  script: vimhelp.py
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

